services:
  db:
    image: mysql:8.0
    container_name: cdp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: cdp_lite
      MYSQL_USER: cdp_user
      MYSQL_PASSWORD: cdp12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: